name: subit_training_job

submit_training_job:
  needs: [build_image_push_to_ECR]
  runs-on: [ubuntu-latest]
  container: docker://dvcorg/cml-py3:latest
  steps:
  - uses: actions/checkout@v2
  - name: Fire SageMaker
    id: sm_train
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      PREFIX: ${{ secrets.PREFIX }}
      IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
      GITHUB_SHA: ${{ github.sha }}
    run: |
      pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec sefs tabulate
      python src/training-job.py
      cat details.txt >> report.md
      cml-send-comment report.md
