name: Demo
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          # APP_PEM: ${{ secrets.APP_PEM }}
          # APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/test-trigger-comment"
          # INDICATOR_LABEL: "test-label"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: clone branch of PR
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@master
        with:
          ref: ${{ steps.prcomm.outputs.SHA }}

        # This step is a toy example that illustrates how you can use outputs from the pr-command action
      - name: print variables
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        run: echo "${USERNAME} made a triggering comment on PR# ${PR_NUMBER} for ${BRANCH_NAME}"
        env: 
          BRANCH_NAME: ${{ steps.prcomm.outputs.BRANCH_NAME }}
          PR_NUMBER: ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}
          USERNAME: ${{ steps.prcomm.outputs.COMMENTER_USERNAME }}

  label-pr2:
      runs-on: ubuntu-latest
      steps:
        - name: listen for PR Comments
          uses: machine-learning-apps/actions-chatops@master
          with:
            # APP_PEM: ${{ secrets.APP_PEM }}
            # APP_ID: ${{ secrets.APP_ID }}
            TRIGGER_PHRASE: "/test-trigger-gaurav"
            # INDICATOR_LABEL: "test-label"
          env: # you must supply GITHUB_TOKEN
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          id: prcommg
          # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
        - name: clone branch of PR
          if: steps.prcommg.outputs.BOOL_TRIGGERED == 'true'
          uses: actions/checkout@master
          with:
            ref: ${{ steps.prcommg.outputs.SHA }}

          # This step is a toy example that illustrates how you can use outputs from the pr-command action
        - name: print variables
          if: steps.prcoprcommgmm2.outputs.BOOL_TRIGGERED == 'true'
          run: echo "${USERNAME} made a triggering comment on PR# ${PR_NUMBER} for ${BRANCH_NAME}"
          env: 
            BRANCH_NAME: ${{ steps.prcommg.outputs.BRANCH_NAME }}
            PR_NUMBER: ${{ steps.prcommg.outputs.PULL_REQUEST_NUMBER }}
            USERNAME: ${{ steps.prcommg.outputs.COMMENTER_USERNAME }}

  notify-pr:
      name: notify Notification
      runs-on: ubuntu-latest
      needs: [label-pr2]
      permissions:
        pull-requests: write
      steps:
        - name: notify Notification
          uses: github-actions-up-and-running/pr-comment@v1.0.1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            message: Nice PR!👍